#!/usr/bin/python
# klean
#
# Alex Holehouse
# January 2013
# v 0.1

import string
import argparse	
import sys						
from subprocess import Popen, PIPE

try:
    p = Popen(['xsel','-pi'], stdin=PIPE)
except:
    print "ERROR: xsel could not be started. Ensure it is installed and configured to be called from command line correctly. In Ubuntu this is as simple as 'sudo apt-get install xsel'. For more information see http://www.vergenet.net/~conrad/software/xsel/"
    exit(1)




parser = argparse.ArgumentParser(description='Clear an input string of spaces, newlines, tabs etc, and copy to clipboard')
parser.add_argument('input', metavar='input',  nargs='+',
                        help='input string (in quotation marks)')

args = parser.parse_args()

# get input string
inputString = args.input[0]

# get characters we care about 
charSet = string.printable[:62] # '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

newstring = ""

for i in inputString:
    if i in charSet:
        newstring = newstring+i
        

# finally add the new string to the middle mouse click
p.communicate(input=newstring)
